apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-srv
  namespace: dev
spec:
  ports:
  - nodePort: 30033
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    type: backend
  type: NodePort

