apiVersion: v1
kind: Service
metadata:
  labels:
    app: php
  name: php-srv
  namespace: dev
spec:
  ports:
  - nodePort: 30034
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php
  type: NodePort

